# config file version
apiVersion: 1
datasources:
- name: scylla-datasource
  type: scylladb-scylla-datasource
  orgId: 1
  isDefault: false
  jsonData:
    host: ''
#  secureJsonData:
#    user: 'Scylla-User'
#    password: 'Scylla-Password'
